server:
  port: 9090
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.56.128:2181
    protocol: -1
spring:
  datasource:
    url: jdbc:mysql:///user_database
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
